import './globals.css'
import Provider from './context/client-provider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <main>
          <Provider session={session}> 
            {children}
          </Provider>
        </main>
      </body>
    </html>
  )
}
