import './globals.css'
import Provider from './context/client-provider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  name : "google-site-verification",
  content : "nrd0FgHTQn-22iR8nvMYew7zhsLStdhZMWypdvWC6po"
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <meta name="google-site-verification" content="nrd0FgHTQn-22iR8nvMYew7zhsLStdhZMWypdvWC6po" />
      <body>
        <main className='main-container min-h-screen'>
          <Provider session={session}> 
            {children}
          </Provider>
        </main>
      </body>
    </html>
  )
}
